#+TITLE: A Brief Tutorial for org-mode
#+AUTHOR: Huming.Chen
#+EMAIL: chenhuming@gmail.com
#+OPTIONS: toc:nil
#+STARTUP: showeverything
#+STARTUP: indent
#+OPTIONS: html-postamble:nil

* Outline
  org-mode can do outline.
** Hotkeys
   <TAB>        => switch between FOLDED, CHILDREN and SUBTREE.
   <S-TAB>      => switch between OVERVIEW, CONTENTS and SHOW-ALL.
   <C-RETURN>   => insert new headings with same level as previous.
   <M-UP>       => move subtree up.
   <M-DOWN>     => move subtree down.
   <M-LEFT>     => promote heading.
   <M-RIGHT>    => demote heading.
   <S-M-LEFT>   => promote subtree.
   <S-M-RIGHT>  => demote subtree.
   <C-c ,>      => org-priority.
   <S-UP>       => increase priority of heading.
   <S-DOWN>     => decrease priority of heading.
   <C-c c>      => capture something, continue your work.

* Markup
  org-mode can do markup.
** Font styles
   * bold *           -> *bold*
   / italic /         -> /italic/
   _ underlined _     -> _underlined_
   + strikethrough +  -> +strikethrough+
   = monospaced =     -> =monospaced=
** Bulleted list items
   - list item
   + item-id :: item-content
     - sub-item
       1. also enumerated
       2. if you like
   - [ ] yet to be done
   + [X] item which is done
** Links
   [[https://orgmode.org][link-to-web: orgmode.org]]
   [[file:~/.emacs.d/elisp/init-org.el::;;; Code][link-to-file-position: init-org.el]]
*** Hotkeys
    <C-c C-l>  => insert all kinds of links.
    <C-c C-o>  => open thing at point.
** Text block
   #+BEGIN_EXAMPLE
   Text block begins here

   Text block ends here
   #+END_EXAMPLE

   For simplicity, you could use "a colon followed by a space"

   : Text block begins here
   :
   : Text block ends here

* Todo
  org-mode can do GTD stuff.
** Sample todo lists
*** TODO explain todo lists
    DEADLINE: <2019-03-09 Sat>
*** DONE cycle through states
    CLOSED: [2019-03-02 Sat 19:40]
    :LOGBOOK:
    - State "DONE"       from "TODO"       [2019-03-02 Sat 19:36]
    :END:
** Hotkeys
   <S-M-RETURN>  => insert todo headings.
   <C-c C-t>     => change todo state.
   <C-c C-d>     => insert deadline for todo item.
   <C-c a>       => open org-agenda.
   <S-UP>        => modify timestampe.
   <S-DOWN>      => modify timestampe.
   <S-LEFT>      => modify timestampe.
   <S-RIGHT>     => modify timestampe.

* Tables
  org-mode can do tables
** Sample table
   |------+----------------|
   | Some | Data           |
   |------+----------------|
   |   12 | buckle my shoe |
   |------+----------------|
   |   34 | shut the door  |
   |------+----------------|
** Hotkeys
   <C-c |>      => create a table, or convert region into a table.
   <|>          => starts a row
   <|->         => starts a horizontal separator line
   <TAB>        => re-align the table
   <M-UP>       => move row up.
   <M-DOWN>     => move row down.
   <M-LEFT>     => move column lef.
   <M-RIGHT>    => move column right.
   <S-M-LEFT>   => delete column.
   <S-M-RIGHT>  => insert column.

* Export
  org-mode can export to HTML, LaTeX, PDF etc.
** Meta-data
   #+AUTHOR:
   #+EMAIL:
   #+STARTUP:
   #+OPTIONS:
   #+HTML_HEAD: <style type="text/css">div.org-src-container{border:1px solid green;width:50%;float:left;}</style>
   #+HTML_HEAD: <style>pre.src {background-color: #eff0f1;margin:0 0 0 0;}</style>
   #+HTML_HEAD: <style type="text/css">div.figure{border:1px solid green;overflow:auto;}</style>
   #+ATTR_HTML: :style border:12px solid black;float:right;
   #+ATTR_HTML: :style border:2px solid red;float:right; :width:50%
** More settings
   [[https://orgmode.org/manual/Export-Settings.html#Export-Settings][Export-Settings]]
   [[https://orgmode.org/manual/HTML-Export.html#HTML-Export][HTML-Export]]
** Hotkeys
   <C-c C-e>  => org-export

* Source code
  org-mode can embed scripts and run them.
** Sample script
   #+BEGIN_SRC ruby
   def fact(n)
     if n == 0
       1
     else
       n * fact(n-1)
     end
   end

   fact(5)
   #+END_SRC

   #+RESULTS:
   : 120
** Hotkeys
   <C-c C-c>  => evaluate script and place result afer #+RESULTS:

* LaTeX integration
  org-mode can do LaTeX.
** Sample LaTeX
   - Characters: \alpha \rightarrow \beta
   - $O(n \log n)$
