* Outline
  org-mode can do outline.
** Hotkeys
   <TAB>       => switch between FOLDED, CHILDREN and SUBTREE.
   <S-TAB>     => switch between OVERVIEW, CONTENTS and SHOW-ALL.
   <C-RETURN>  => insert new headings with same level as previous.

* Markup
  org-mode can do markup.
** Font styles
   * bold *           -> *bold*
   / italic /         -> /italic/
   = verbatim =       -> =verbatim=
   + strikethrough +  -> +strikethrough+
** Bulleted list items
   - bulleted
   - list
   - items
** Links
   [[https://orgmode.org][link-to-web: orgmode.org]]
   [[file:init-org.el::;;; Code][link-to-file-position: init-org.el]]
*** Hotkeys
   <C-c C-l>  => insert all kinds of links.
   <C-c C-o>  => open thing at point.

* Todo
  org-mode can do GTD stuff.
** Sample todo lists
*** TODO explain todo lists
    DEADLINE: <2019-03-09 Sat>
*** DONE cycle through states
    CLOSED: [2019-03-02 Sat 19:40]
    :LOGBOOK:
    - State "DONE"       from "TODO"       [2019-03-02 Sat 19:36]
    :END:
** Hotkeys
   <S-M-RETURN>  => insert todo headings.
   <C-c C-t>     => change todo state.
   <S-UP>        => modify timestampe.
   <S-DOWN>      => modify timestampe.
   <S-LEFT>      => modify timestampe.
   <S-RIGHT>     => modify timestampe.
   <C-c C-d>     => insert deadline for todo item.
   <C-c a>       => open org-agenda.

* Tables
  org-mode can do tables
** Sample table
  |------+----------------|
  | Some | Data           |
  |------+----------------|
  |   12 | buckle my shoe |
  |------+----------------|
  |   34 | shut the door  |
  |------+----------------|
** Hotkeys
   <C-c |>    => create a table, or convert region into a table.
   <TAB>      => re-align the table
   <M-UP>     => move row up.
   <M-DOWN>   => move row down.
   <M-LEFT>   => move column lef.
   <M-RIGHT>  => move column right.
   <|>        => starts a row
   <|->       => starts a horizontal separator line

* Export
  org-mode can export to HTML, LaTeX, PDF etc.
** Hotkeys
   <C-c C-e>  => org-export
** Meta-data for export
   #+title: A Brief Tutorial for org-mode
   #+options: toc:nil

* Source code
  org-mode can embed scripts and run them.
** Sample script
   #+begin_src ruby
   def fact(n)
     if n == 0
       1
     else
       n * fact(n-1)
     end
   end

   fact(5)
   #+end_src

   #+RESULTS:
   : 120
** Hotkeys
   <C-c C-c>  => evaluate script and place result afer #+RESULTS:

* LaTeX integration
  org-mode can do LaTeX.
** Sample LaTeX
   - Characters: \alpha \rightarrow \beta
   - $O(n \log n)$

   \begin{align*}
     3 * 2 + &= 6 + 1 \\
             &= 7
   \end{align*}
