;;; init-gptel.el --- config gptel for querying llm. -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

;; ============================================================================
;; Package Configuration
;; ============================================================================

;;; LLM client
;;  "gptel"         => start a LLM session
;;  "C-c RET"       => send to LLM
;;  "gptel-send"    => send to LLM
;;  "gptel-rewrite" => Rewrite, refactor
(use-package gptel
  :ensure t
  :config
  (progn
    (setq gptel-log-level 'info
          gptel-confirm-tool-calls nil
          gptel-model 'deepseek-v4-flash
          ;; Randomness in response text, 0 to 2
          gptel-temperature 0
          gptel-backend
          (gptel-make-deepseek "DeepSeek"
            ;; set stream to nil when using zai-org/GLM-5.2
            :stream t
            :key ""))
    ;; free 2000 request per-day, each model 500
    (gptel-make-openai "Free"
      :host "api-inference.modelscope.cn"
      :stream t
      :key ""
      :models '(deepseek-ai/DeepSeek-V3.2
                ZhipuAI/GLM-5.2))
    (gptel-make-ollama "Ollama"
      :stream t
      :models '(qwen2.5:7b))))

;; ============================================================================
;; Additional Packages
;; ============================================================================

(use-package gptel-agent
  :ensure t
  :config
  (progn
    (gptel-agent-update)
    ;; add project related information into llm context, e.g: coding guideline, etc.
    (require 'gptel-context)
    (gptel-add-file (expand-file-name "~/.emacs.d/contexts"))
    ;; add task-completion-rules into llm context
    (gptel-add-file
     (expand-file-name
      "task-completion-rules.md"
      (file-name-directory
       (or (locate-library "gptel-agent-harness")
           (error "gptel‑agent‑harness not found")))))
    ;; add agent skills, e.g: https://github.com/anthropics/skills
    (add-to-list 'gptel-agent-skill-dirs "~/.emacs.d/skills")
    ;; suppress gptel warning
    (add-to-list 'warning-suppress-types '(gptel))
    (require 'gptel-agent-harness)
    (gptel-agent-harness-mode 1)
    ;; define and use gptel-telegram
    (gptel-agent-harness-extras--define-agent telegram ("chrome"))
    (add-to-list 'gptel-agent-harness-context-windows '("openai/gpt-oss-120b" . 128000))))

(use-package gptel-cpp-complete
  :ensure t
  :config
  (when (display-graphic-p)
    (dolist (c-mode-hook '(c-mode-common-hook c-ts-mode-hook c++-ts-mode-hook))
      (add-hook c-mode-hook #'gptel-cpp-complete-mode))))

(defun my/gptel-clean-temp-files ()
  "Remove old gptel temp files owned by current user."
  (let* ((tmpdir temporary-file-directory)
         (patterns '("^gptel-curl" "^gptel-agent"))
         (max-age (* 30 60))
         (uid (user-uid))
         (deleted-count 0))
    (dolist (file (directory-files tmpdir t))
      (when (and (file-exists-p file)
                 (cl-some (lambda (pat)
                            (string-match-p pat (file-name-nondirectory file)))
                          patterns))
        (let* ((attrs (file-attributes file))
               (owner (nth 2 attrs)) ;; uid
               (mtime (nth 5 attrs))
               (age (float-time (time-subtract (current-time) mtime))))
          (when (and (eq owner uid)
                     (> age max-age))
            (ignore-errors
              (if (file-directory-p file)
                  (delete-directory file t)
                (delete-file file))
              (setq deleted-count (1+ deleted-count)))))))
    (when (> deleted-count 0)
      (message "[%s] Cleaned up %d old gptel temp files"
               (format-time-string "%Y-%m-%d %H:%M:%S")
               deleted-count))))

;; clean temporary files generated by gptel
(run-at-time "0" 600 #'my/gptel-clean-temp-files)

;; ============================================================================
;; Custom Prompts and Variables
;; ============================================================================

(defconst my-gptel--default-prompt
  "You are a large language model and a helpful assistant. Respond concisely."
  "Default system prompt for general QA tasks.")

(defvar my-gptel--user-prompt ""
  "Current user prompt for gptel requests.")

;; ============================================================================
;; Core Functions
;; ============================================================================

(defun my-gptel--request ()
  "Initiate a gptel request with the current user prompt."
  (gptel--sanitize-model)
  (gptel-request my-gptel--user-prompt
    :system my-gptel--default-prompt
    :stream t
    :callback #'my-gptel--response-callback))

(defun my-gptel--response-callback (response info)
  "Callback function for gptel requests.
RESPONSE is the LLM response text.
INFO contains metadata about the request."
  (if (not response)
      (message "gptel-dwim failed with message: %s" (plist-get info :status))
    (display-buffer
     (with-current-buffer (get-buffer-create "*LLM response*")
       (let ((inhibit-read-only t))
         (deactivate-mark)
         (visual-line-mode 1)
         (goto-char (point-max))
         (ignore-errors
           (insert response))
         (markdown-mode)
         (gptel-mode)
         (current-buffer)))
     '((display-buffer-reuse-window
        display-buffer-pop-up-window)
       (reusable-frames . visible)))))

(defun gptel-dwim (prompt)
  "Request a response from the `gptel-backend' for PROMPT.
The request is asynchronous, this function returns immediately.

If PROMPT is:
- current-prefix-arg enabled, create a full prompt from both minibuffer
  and active_region/symbol_at_point suitable for sending to the LLM.
- a string, it is used to create a full prompt suitable for
  sending to the LLM."
  (declare (indent 1))
  (interactive (list (smart/read-from-minibuffer "Ask ChatGPT")))

  (let ((local-prefix-arg
         (if (listp current-prefix-arg) (car current-prefix-arg) current-prefix-arg))
        (context (smart/dwim-at-point)))

    ;; Add context from active region or symbol at point if prefix arg is given
    (when local-prefix-arg
      (and context
           (setq prompt (concat prompt "\n\n" context))))

    (setq my-gptel--user-prompt prompt)
    (message "Querying %s..." (gptel-backend-name gptel-backend))
    (my-gptel--request)))

;; ============================================================================
;; Preset Configurations
;; ============================================================================

;;; Preset selection
;;  "gtpel-qa"         => general QA/code-completion
;;  "gptel-plan"       => handle complicated tasks with read-only tools
;;  "gptel-agent"      => handle complicated tasks

;; Preset for general QA tasks
(gptel-make-preset 'gptel-qa
  :description "A preset optimized for general QA tasks"
  :backend "Free"
  :model gptel-model
  :stream t
  :system my-gptel--default-prompt
  :tools nil
  :temperature 1)

;; ============================================================================
;; Provide the module
;; ============================================================================

(provide 'init-gptel)
;;; init-gptel.el ends here
