;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        *table--cell-delete-char
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        comment-dwim
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        ))
