#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Telegram ↔ Emacs gptel-agent Bridge (File-based Streaming Version)

Overview
--------
This script implements a Telegram bot that acts as a bridge to an Emacs
gptel-agent. It allows sending prompts from Telegram and receiving
streamed responses generated by the agent.

Instead of relying on stdout streaming or HTTP callbacks, this version
uses a file-based approach for maximum stability:

    Telegram → Python → Emacs (gptel-agent)
                            ↓
                      append to file
                            ↓
                  Python polls file changes
                            ↓
               Telegram message updates

Key Features
------------
- Streaming-like experience in Telegram via message editing
- No HTTP server required
- No fragile stdout/pipe handling
- Works reliably with emacsclient in daemon mode
- Supports proxy for restricted networks
- Cleans up old gptel-agent buffers before starting

Configuration
-------------
- TOKEN: Telegram bot token (from BotFather)
- AUTHORIZED_USER_ID: Only this user can interact with the bot
- PROXY_URL: SOCKS5/HTTP proxy (e.g., http://127.0.0.1:1080)
- AGENT_OUTPUT_FILE: File used for streaming agent output
- TELEGRAM_MAX_LENGTH: Safe limit for Telegram messages (~4000)

Dependencies
------------
- python-telegram-bot >= v20
- Emacs with gptel and gptel-agent configured
- emacsclient (Emacs daemon must be running)
- Optional: python-telegram-bot[socks] for proxy support

    pip install python-telegram-bot --upgrade

Design Decisions
----------------
Why file-based instead of stdout streaming?

- emacsclient output buffering is unreliable
- force-output is not portable across Emacs versions
- subprocess pipes can block or deadlock
- file polling is simple, observable, and robust

Trade-offs:
- Slight latency (poll interval)
- Requires filesystem access
- Not true token-level streaming (chunk-based)

Limitations
-----------
- Single active session (shared output file)
- Large outputs are truncated to TELEGRAM_MAX_LENGTH
- Telegram rate limits may apply on frequent edits
- No built-in cancellation (/stop) yet

Possible Improvements
---------------------
- Per-user or per-session output files (multi-user support)
- Smarter diffing (only send delta instead of full text)
- Overflow handling (split into multiple Telegram messages)
- Add /stop command to terminate agent
- Switch to file watcher (inotify) instead of polling

Security Notes
--------------
- Never commit your TOKEN to version control
- Regenerate token via BotFather if exposed
- Restrict access using AUTHORIZED_USER_ID

Author Intent
-------------
This implementation prioritizes reliability and simplicity over
low-latency streaming, making it suitable for constrained environments
(e.g., behind proxies or unstable IPC setups).

"""

import subprocess
import os
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    ContextTypes,
    CommandHandler,
    MessageHandler,
    filters,
)
import logging
import time


# ================= CONFIG =================
# Replace with your actual token from BotFather
TOKEN = 'xxxxx'
# Replace with your actual Telegram User ID
AUTHORIZED_USER_ID = 12345678

PROXY_URL = "http://127.0.0.1:1080"

TELEGRAM_MAX_LENGTH = 4000
AGENT_OUTPUT_FILE = os.path.expanduser("~/workspace/agent-session.md")
# =========================================

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)


# ---------- Emacs agent ----------
def start_agent(prompt: str):
    prompt = prompt.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

    elisp = f"""
(progn
  (dolist (b (buffer-list))
    (when (string-match-p "^\\*gptel-agent:" (buffer-name b))
      (kill-buffer b)))

  (defun extract_agent_response (beg end)
    (let ((pos beg)
          (result "")
          (last-prop nil))
      (while (< pos end)
        (let* ((next (next-single-property-change pos 'gptel nil end))
               (next (or next end))
               (prop (get-text-property pos 'gptel))
               (chunk (buffer-substring-no-properties pos next)))
          (when (and last-prop
                     (not (eq prop last-prop))
                     (> (length result) 0)
                     (not (string-suffix-p "\n" result))
                     (not (string-prefix-p "\n" chunk)))
            (setq result (concat result "\n")))
          (when (eq prop 'response)
            (setq result (concat result chunk)))
          (setq last-prop prop)
          (if (= pos next)
              (setq pos (1+ pos))
            (setq pos next))))
      result))

  (defun append-agent-output-to-file (beg end)
    "Append the latest gptel response to a file."
    (let ((txt (extract_agent_response beg end)))
      (with-temp-buffer
        (insert "\\n---\\n")
        (insert (format "Date: %s\\n" (current-time-string)))
        (insert txt)
        (append-to-file (point-min) (point-max) "{AGENT_OUTPUT_FILE}"))))

  (remove-hook 'gptel-post-response-functions #'append-agent-output-to-file)
  (add-hook 'gptel-post-response-functions #'append-agent-output-to-file)

  (gptel-agent "./")
  (let ((buf (seq-find
               (lambda (b) (string-match-p "^\\*gptel-agent:" (buffer-name b)))
               (buffer-list))))
    (when buf
      (with-current-buffer buf
        (erase-buffer)
        (insert "{prompt}")
        (gptel-send)))))
"""

    subprocess.Popen(
        ["emacsclient", "--eval", elisp],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )


# ---------- Send in batch ----------
async def send_in_chunks(text: str, update: Update):
    if not text.strip():
        return

    chunks = [
        text[i:i + TELEGRAM_MAX_LENGTH]
        for i in range(0, len(text), TELEGRAM_MAX_LENGTH)
    ]

    for chunk in chunks:
        await update.message.reply_text(chunk)
        time.sleep(0.3)  # avoid flooding telegram


# ----------Python polling ----------
async def poll_agent_output(update: Update):
    last_size = 0
    max_polls = 120  # about 2 minutes
    poll_count = 0

    msg = await update.message.reply_text("🧠 Thinking...")

    while poll_count < max_polls:
        if os.path.exists(AGENT_OUTPUT_FILE):
            size = os.path.getsize(AGENT_OUTPUT_FILE)
            if size > last_size:
                with open(AGENT_OUTPUT_FILE, "r") as f:
                    f.seek(last_size)
                    new_text = f.read()
                    if new_text.strip():
                        try:
                            await send_in_chunks(new_text, update)
                        except Exception:
                            pass
                last_size = size
                last_change_time = time.time()
        time.sleep(1)
        poll_count += 1

    if os.path.exists(AGENT_OUTPUT_FILE):
        os.remove(AGENT_OUTPUT_FILE)

    await update.message.reply_text("✅ Agent finished.")


# ---------- Telegram handlers ----------
async def start(update: Update):
    await update.message.reply_text("🚀 Emacs Streaming Agent Ready (Proxy Enabled)")


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.message.from_user.id != AUTHORIZED_USER_ID:
        await update.message.reply_text("Unauthorized")
        return

    prompt = update.message.text

    if os.path.exists(AGENT_OUTPUT_FILE):
        os.remove(AGENT_OUTPUT_FILE)

    start_agent(prompt)

    await poll_agent_output(update)


# ---------- Main ----------
def main():
    app = (
        ApplicationBuilder()
        .token(TOKEN)
        .proxy(PROXY_URL)
        .build()
    )

    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))

    print(f"🚀 Telegram Streaming Agent Running with proxy {PROXY_URL}")
    app.run_polling()


if __name__ == "__main__":
    main()
